### ISSUE TITLE
[Question] About lifecycle of models

### ISSUE THREAD

**Issue by cian0** [Chaoses-Ib/ComfyScript#11]
Hi I haven't tried it yet but genuinely interested, my question would be about the loaded model's lifecycles. In comfy whenever i switch workflows it will have to reload the models because they have different node IDs, just wondering if using this library would fix that if I were to create a repository of workflows..

**Comment by Chaoses-Ib** [comment]
Yes, you can control when to free the models. You should use `with torch.inference_mode()` instead of `with Workflow()` to avoid having similar behavior to ComfyUI.

By the way, I didn't find much docs about ComfyUI's model management, but it looks like it won't unload a model if only the node ID changed, instead, it's only unloaded if the reference count becomes zero.

**Comment by Chaoses-Ib** [comment]
See https://github.com/Chaoses-Ib/ComfyScript/issues/21#issuecomment-1936482022 for unloading models.

**Comment by cian0** [comment]
Awesome thanks!
