### ISSUE TITLE
Save Image returns what?

### ISSUE THREAD

**Issue by ghostsquad** [Chaoses-Ib/ComfyScript#47]
I'm a bit confused by this line in the examples that let's you choose an image to hiresfix:

```
image_batches.append(SaveImage(VAEDecode(latent, vae), f'{seed} {color}'))
```

AFAIK `SaveImage` doesn't return anything. What am I missing?

**Comment by Chaoses-Ib** [comment]
In real mode, all output nodes return dicts. That's why the web UI can retrieve results after generation. Actually this is shown in the docs of real mode:
```python
print(SaveImage(image, 'ComfyUI'))
# {'ui': {'images': [
#   {'filename': 'ComfyUI_00001_.png',
#     'subfolder': '',
#     'type': 'output'}
# ]}}
```

The example you mentioned is using virtual mode. In virtual mode, the dict is wrapped into a class called `NodeOuput`, so that one can await it.

**Comment by ghostsquad** [comment]
ah, thanks! that makes sense
