### ISSUE TITLE
grab workflow from image

### ISSUE THREAD

**Issue by ghostsquad** [Chaoses-Ib/ComfyScript#49]
is there a way to grab/load the ComfyScript from an existing image?

**Comment by Chaoses-Ib** [comment]
Yes. Actually I have a widget for this. Unfortunately, there is a bug in the old versions of VS Code Notebook and one cannot drag files into it. It's fixed in the preview version and I'm using it. A stable version should be released now. I'll upload the code later. Though it still can't show syntax highlights properly in VS Code.

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/50246090/e66aea3a-fbe4-4e16-9319-e84acbe43190)

![image](https://github.com/Chaoses-Ib/ComfyScript/assets/50246090/07636327-ba1b-4979-bfcf-19bfe214f2f4)

**Comment by ghostsquad** [comment]
cool thanks!

**Comment by Chaoses-Ib** [comment]
It's now uploaded. ComfyScript / ComfyUI / Stable Diffusion web UI images and workflow JSON are supported.

Docs: https://github.com/Chaoses-Ib/ComfyScript/blob/main/docs/UI/Solara.md

**Comment by ghostsquad** [comment]
love it! thanks

**Comment by ghostsquad** [comment]
mm... tried using it, got this:

```
Set state = <ResultState.RUNNING: 4> for key '2' (previous value was <ResultState.STARTING: 2>) (2804838762640)
No render phase triggered, already rendering
'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Traceback (most recent call last):
  File "e:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\solara\hooks\use_thread.py", line 84, in runner
    value = f()
            ^^^
  File "e:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\solara\components\file_drop.py", line 75, in handle_file
    on_file(wired_files[0])
  File "E:\custom_nodes\ComfyScript\src\comfy_script\ui\solara\metadata.py", line 20, in on_file
    image = Image.open(bin)
            ^^^^^^^^^^^^^^^
  File "e:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3274, in open
    filename = os.path.realpath(os.fspath(fp))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 675, in realpath
  File "<frozen ntpath>", line 542, in normpath
  File "<frozen os>", line 826, in fsdecode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Set state = <ResultState.ERROR: 5> for key '2' (previous value was <ResultState.RUNNING: 4>) (2804838612816)
Render phase: 2 'main' of _AppLayoutEmbed(children = ...)
```

Dragging that same image to the UI works fine.

**Comment by Chaoses-Ib** [comment]
Fixed. Forgot to test images after adding support for JSON.

**Comment by ghostsquad** [comment]
awesome! just tried it, and it works wonderfully. 🙌
