### ISSUE TITLE
Prompts Everywhere -- KeyError: 'CONDITIONING' 

### ISSUE THREAD

**Issue by cihangoksu** [Chaoses-Ib/ComfyScript#78]
Hi,

I am using 'Prompts Everywhere' in my workflow, and transpiler shoots the following error (likely because +ve and -ve input names changed to CONDITIONING after they connect):

![image](https://github.com/user-attachments/assets/9b2b67e4-5330-49fb-b48c-596d0c6f95b7)

![image](https://github.com/user-attachments/assets/7035db48-af5c-4089-885c-fa39df01ff55)

Is there a workaround to solve this error please? Thank you...

Cheers,
Cihan

**Comment by Chaoses-Ib** [comment]
According to my test, Prompts Everywhere will lose connections after saving to API format:

Before:

![image](https://github.com/user-attachments/assets/3d22bb2a-467f-48ea-b817-e515c598d5aa)

Save in API format and load again:

![image](https://github.com/user-attachments/assets/3b10334c-59e0-4414-a8c8-c57d08b88d2c)

It turns out that UE Nodes doesn't support API format: https://github.com/chrisgoringe/cg-use-everywhere/issues/217 It can't be fixed at ComfyScript side.
