### ISSUE TITLE
Doc Request - how to run script.

### ISSUE THREAD

**Issue by beanhilton** [Chaoses-Ib/ComfyScript#8]
Hi. Python noob here.

I understand how to use comfyUI, and regular custom nodes. I have installed comfyscript in custom_nodes. I can code (a bit). 

I don't use python, but I can follow what the scripts are doing and I'm pretty confident I could write some, so this looks really useful.

I may have missed something, but in the docs says "With the runtime, you can run ComfyScript like this:"... but then just shows another script. 

Could I request a line or two in the docs to explain how to actually run one of the examples already given. Its probably obvious when you know - I'm just not seeing it.
Does it matter where the script files are saved?
Do I need to have comfyui running? 
Do I need a workflow open?
How do I run the script?

Thanks

**Comment by Chaoses-Ib** [comment]
> Could I request a line or two in the docs to explain how to actually run one of the examples already given.

There is a Jupyter Notebook example: [runtime.ipynb](https://github.com/Chaoses-Ib/ComfyScript/blob/main/runtime.ipynb). You need to clone this repository with git, then use IDEs like VS Code to open the cloned directory, and then open `runtime.ipynb`.

> Does it matter where the script files are saved?

Yes. If the script file is placed at the root of this repository, then you just need to `import script.runtme`. However, because ComfyScript is not installed as a site package, if you want to import it from outside of the repository, you have to add the path to the repository to `sys.path` manually. I'll publish ComfyScript as a pip package in v0.3 or v0.4 to solve this.

> Do I need to have comfyui running?

Yes for now. v0.3 will introduce a "real mode", with which ComfyScript will run nodes itself. See #6 for details. BTW, you can also use a remote server by `load('http://1.2.3.4:8188/')`.

> Do I need a workflow open?

No. You only need to start ComfyUI's server, no need to open the web UI.

> How do I run the script?

Just as the example shows. When a `with Workflow` block is finished, the workflow will be sent to the queue. You can also queue it manually, see [runtime.ipynb](https://github.com/Chaoses-Ib/ComfyScript/blob/main/runtime.ipynb).

**Comment by beanhilton** [comment]
Much appreciated, thanks for the quick reply.

**Comment by Chaoses-Ib** [comment]
[v0.3](https://github.com/Chaoses-Ib/ComfyScript/releases/tag/v0.3.0) is now released. After installing the package by `python -m pip install -e .`, you can `import comfy_script` anywhere, no longer limited to the root directory of the repository.

**Comment by Chaoses-Ib** [comment]
> Do I need to have comfyui running?

https://github.com/Chaoses-Ib/ComfyScript/releases/tag/v0.4.0 is released and now the runtime can start a server by itself.

I'm going to close this issue as most info are outdated now.
